"""empty message

Revision ID: 919b69321c7e
Revises: 
Create Date: 2019-11-18 13:41:05.836275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919b69321c7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last__seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last__seen')
    op.drop_column('user', 'about')
    # ### end Alembic commands ###
