"""empty message

Revision ID: 94995958afa4
Revises: abbe44b755f5
Create Date: 2019-12-02 18:31:35.285917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94995958afa4'
down_revision = 'abbe44b755f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('notes', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'notes')
    # ### end Alembic commands ###
